@startuml
'https://plantuml.com/component-diagram

left to right direction

node "Клиент" {
  [Главное окно]

  package "Подсистема демонстрации теории" {
    [Модуль демонстрации теории]
  }
  [Модуль настройки] - [Модуль демонстрации теории]
  [Модуль демонстрации теории] -- [Главное окно]

  package "Подсистема демонстрации алгоритмов" {
    [Модуль демонстрации алгоритма Краскала]
    [Модуль демонстрации алгоритма проверки включения пути в цикл]
  }
  [Модуль демонстрации алгоритма проверки включения пути в цикл] - [Модуль демонстрации алгоритма Краскала]
  [Модуль демонстрации алгоритма Краскала] -- [Главное окно]

  package "Подсистема тестирования" {
    [Модуль тестирования]
    [Модуль просмотра статистики]
    database Статистика
  }
  [Модуль просмотра статистики] - [Модуль тестирования]
  [Модуль просмотра статистики] - Статистика
  [Модуль настройки] - [Модуль тестирования]
  [Модуль тестирования] -- [Главное окно]

  [Модуль настройки]
}

@enduml