@startuml
'https://plantuml.com/class-diagram

class MainWindow {
    - Ui::MainWindow * ui

    + MainWindow(QWidget *)
    + ~MainWindow() override

    - void displayHelloText()
    - void on_theoryButton_clicked()
    - void on_demoButton_clicked()
    - void on_testingButton_clicked()
}

class TheorySystem {
    - Ui::TheorySystem * ui

    + TheorySystem(QWidget *)
    + ~TheorySystem()

    - void displaySource()
    - void on_prevPageButton_clicked()
    - void on_nextPageButton_clicked()
    - void urlChanged()
    - void on_settingsMenuBar_triggered()
}
TheorySystem -up- MainWindow

class TheorySettingsWindow {
    - Ui::TheorySettingsWindow * ui

    + TheorySettingsWindow(QWidget *)
    + ~TheorySettingsWindow() override

    - void on_changeTheorySourceButton_clicked()
    - void on_saveButton_clicked()
}
TheorySettingsWindow -up- MainWindow



@enduml