@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Пользователь: as user

rectangle "Подсистема демонстрации теории" {
    user --> (Изучить теорию)
    (Изучить теорию) <.. (Перейти к следующей странице) : extend
    (Изучить теорию) <.. (Перейти к предыдущей странице) : extend
    (Изучить теорию) <.. (Перейти к начал подраздела) : extend
    (Изучить теорию) <.. (Перейти к содержанию) : extend

    user --> (Изменить настройки теории)
    (Изменить настройки теории) <.. (Изменить путь к файлу с теорией) : extend
}

rectangle "Подсистема демонстрации алгоритмов" {
    user --> (Просмотреть демонстрацию)
    (Просмотреть демонстрацию) <.. (Перейти в начало демонстрации) : extend
    (Просмотреть демонстрацию) <.. (Пропустить пошаговую демонстрацию) : extend
}

rectangle "Подсистема тестирования"{
    user --> (Пройти тестирование)
    (Пройти тестирование) <.. (Просмотреть правила тестирования) : extend
    (Пройти тестирование) ..> (Авторизоваться) : include
    (Пройти тестирование) ..> (Ответить на вопрос) : include
    (Пройти тестирование) ..> (Просмотреть результат) : include

    user --> (Изменить настройки тестирования)
    (Изменить настройки тестирования) <.. (Изменить количество вопросов) : extend
    (Изменить настройки тестирования) <.. (Изменить путь к файлу с вопросами) : extend

    user --> (Просмотреть статистику\nпо пользователям)
    (Просмотреть статистику\nпо пользователям) <.. (Отфильтровать статистику) : extend

    user --> (Просмотреть помощь по\nдобавлению вопросов\nв базу тестирования)
}

@enduml